version: '3.0'
services:
  app:
    image: node:14.17.6
    command: sh -c "npm install -g npm@8.19.2 --force && npm install --force && npm run start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./frontend:/app
  backend:
    image: node:14.17.6
    command: sh -c "npm install -g npm@8.19.2 --force && npm install --force && npm run start"
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - ./backend:/app
  proxy :
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx:/etc/nginx/conf.d